SET NAMES UTF8;
DROP DATABASE IF EXISTS strategy;
CREATE DATABASE strategy CHARSET=UTF8;
USE strategy;
CREATE TABLE strategy_list(
    lid INT PRIMARY KEY AUTO_INCREMENT,
    lpic VARCHAR(360),
    lname VARCHAR(240),
    ltext VARCHAR(2048),
    lbtn VARCHAR(240)
);
INSERT INTO strategy_list VALUES
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy03.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy02.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题'),
(NULL,'../images/strategy01.jpg','6.87版本后新眼位详解攻略','在经历了ESL-ONE马尼拉联赛之后，Dota2迎来了6.87版本……','进入专题');
